EFDSC/Controllers/ClubInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EFDSC.Controllers
{
    public class ClubInfoController : Controller
    {
        // GET: ClubInfo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult ClubConstitution()
        {
            return View();
        }

        public ActionResult CodeOfConduct()
        {
            return View();
        }

        public ActionResult ParentGuidelines()
        {
            return View();
        }

        public ActionResult ClubHistory()
        {
            return View();
        }
    }
}

EFDSC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EFDSC - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Custom.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style="padding-top: 0px;">
    <div id="logo">
        <img class="logo center-block" src="@Url.Content("~/Content/Images/EFDSCLogo.jpg")" alt="Logo">
    </div>
    <div class="navbar navbar-inverse" style="border-radius: 0px;">
        <div class="container" style="width:100%;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", htmlAttributes: new { style = "color: #FEDD02" })</li>
                    <li>@Html.ActionLink("Contacts", "Contacts", "Home", htmlAttributes: new { style = "color: #FEDD02" })</li>
                    @*<li>@Html.ActionLink("About", "About", "Home", htmlAttributes: new { style = "color: #FEDD02" })</li>*@
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color: #FEDD02;">Club Info <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("About EFDSC", "About", "ClubInfo")</li>
                            <li>@Html.ActionLink("Club Constitution", "ClubConstitution", "ClubInfo")</li>
                            <li>@Html.ActionLink("Code Of Conduct", "CodeOfConduct", "ClubInfo")</li>
                            <li>@Html.ActionLink("Parent/Carer Guidelines", "ParentGuidelines", "ClubInfo")</li>
                            <li>@Html.ActionLink("Club History", "ClubHistory", "ClubInfo")</li>
                            @*<li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">One more separated link</a></li>*@
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="padding: 0% 10%;">
        @RenderBody()
        <hr />
        <footer>
            <div style="text-align: center;">
                <span>&copy; @DateTime.Now.Year - Epping Forest District Swimming Club</span>
                <img src="@Url.Content("~/Content/Images/follow-facebook.gif")" href="#" alt="Follow us on Facebook"/>
                <img src="@Url.Content("~/Content/Images/follow-twitter.gif")" href="#" alt="Follow us on Twitter"/>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>